### PR TITLE
Removing Control.from_existing

### PR DESCRIPTION
**Pull request by bob-white**
It has been superseded by Control.wrap, should solve #73

### CODE REVIEW

**Comment by bob-white** [comment]
I think this is safe, but I don't have anything that is using `PanelFactory` which was the only item I could find using `from_existing` so I could do some rather minimal testing.

Plus I'm not sure if anyone else out there is actually relying on `from_existing` in their local code.

**Comment by theodox** [comment]
I think this is OK, although we should wait until I can put up a notice about it before we merge it into main. Maybe we should include an extension of gui.derive along with this this and then push the pair as a point release?

**Comment by bob-white** [comment]
We could do an interim step where we leave `from_existing` as an alias to `wrap` and add a deprecation warning.

**Comment by theodox** [comment]
In the interest of preventing issues from propagating, I'd just make it fail instead of warning. We can include a fix note in the comment.

**Pull request merged**
