### PR TITLE
Event handler stash.

### PR DESCRIPTION
**Pull request by bob-white**
A possible solution to #40

Instead of trying to infer some kind of stash object like my last solution, this one requires that you explicitly pass a stash object along with the handler.

Updated the example from the issue .
```python
from maya import cmds
from mGui import gui, forms, lists
from mGui.observable import ObservableCollection
from mGui.bindings import bind

def event_test():
    with gui.BindingWindow(title = 'example window') as test_window:
        bound = ObservableCollection("A", "B")

        with forms.VerticalForm() as main:
            gui.Text(label = "The following items don't have vertex colors")
            list_view = lists.VerticalList()
            list_view.bind.collection < bind() < bound
            with forms.HorizontalStretchForm('buttons'):
                refresh = gui.Button('refresh', l='Refresh')
                close = gui.Button('close', l='Close')

    def close_window(*_, **__):
        cmds.deleteUI(test_window)

    def refresh_window(*_, **__):
        list_view.redraw()

    # We pass both the handler, and the object to stash it on
    refresh.command += refresh_window, test_window
    close.command += close_window, test_window
    return test_window

win = event_test()
win.show()
```
Updated the example to use the `+=` syntax, as per the suggestion.

### CODE REVIEW

**Comment by theodox** [comment]
this looks neater.  Maybe at that point we don't need the `*=` and we instead catch that the arg list is a tuple?

**Comment by bob-white** [comment]
Oh I like that, it didn't even occur to me.

**Comment by bob-white** [comment]
Updated it so that we only need to care about `+=` and `-=`. 
Added some tests for the new behavior.

**Comment by theodox** [comment]
Do you want to add docs, or shall I?

**Comment by theodox** [comment]
Doh, sorry

**Comment by bob-white** [comment]
Updated the docs, and the basicList example. 

Also realized that using this we can bind a `lambda`, though only 1 because the `__name__` field is always `<lambda>` So it will overwrite if you try to bind a second one.

**Comment by theodox** [comment]
why not detect it and use `id (lambda)` as the key?

**Comment by bob-white** [comment]
Completely forgot about `id` I'll swap that around.
Its probably better to just use `id(handler)` as that would cover all callables.

**Comment by theodox** [comment]
does (id) work on weak refs?

**Comment by bob-white** [comment]
It does, but you get the id of the weakref not the original object's id.

**Pull request merged**
