### PR TITLE
More 2.0 stabilization

### PR DESCRIPTION
**Pull request by theodox**
Includes the rest of bob's changes, plus a minor fix (the new inheritance chain for ImmediateBoundCollection lost its `_BIND_TGT`, which meant that binding to collections was failing.

This needs to be tested against the UL codebase at work to make sure it's feature compatible.

### CODE REVIEW

**Comment by theodox** [comment]
@bob-white  - can you pull this one down, merge it with master locally, and verify that it's in good shape? I'd like to close this PR but I' haven't got the bandwidth to do a cleanroom test on these

**Comment by bob-white** [comment]
I think once #52 gets merged in we should be good to go.
I made some updates to most of the examples over in bob-white/mGui#1. They are based on the code in #52 so would need it merged first to avoid any conflicts.
All of the examples now run without error, and all the tests are still passing.

**Comment by theodox** [comment]
Jeez, looks like I never merged this.  @bob-white  -- shall I pull the trigger?

**Comment by theodox** [comment]
This will be superseded by #62 -- when I merge that I'll finally close this out and nuke 'remove keys'

**Pull request merged**
